### ISSUE TITLE
安装 SmallBear-v3.apk 运行出错

### ISSUE THREAD

**Issue by VilenEera** [daimajia/little-bear-dictionary#7]
```
>adb logcat |grep dictionary

E/AndroidRuntime(21858): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zhan_dui.dictionary/com.zhan_dui.dictionary.GeneralActivity}: java.lang.NullPointerException
E/AndroidRuntime(21858):        at com.zhan_dui.dictionary.fragments.QueryWordFragment.onCreateOptionsMenu(QueryWordFragment.java:106)
E/AndroidRuntime(21858):        at com.zhan_dui.dictionary.fragments.QueryWordFragment.onCreate(QueryWordFragment.java:51)
I/ActivityManager(  415): Process com.zhan_dui.dictionary (pid 21858) (adj 0) has died.
```

**Comment by daimajia** [comment]
重新gradle编译了一下，有兴趣的话重新试试？
